# Generated by Django 4.2.17 on 2025-01-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('services', '0002_shoppingcart_product_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.customer', verbose_name='Customer'),
        ),
        migrations.CreateModel(
            name='ShoppingCart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.shoppingcart', verbose_name='ShoppingCart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('payment_status', models.BooleanField(default=False, help_text='Indicates whether the payment has been completed.', verbose_name='Payment Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bonus', 'Bonus')], max_length=50, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('not_prepared', 'Not Prepared Yet'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='not_prepared', max_length=50, verbose_name='Order Status')),
                ('evaluate', models.CharField(blank=True, choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], default=None, max_length=50, null=True, verbose_name='Evaluate Service')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.address', verbose_name='Address')),
                ('id_cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.shoppingcart_items', verbose_name='ShoppingCart_Item')),
            ],
        ),
    ]
