# Generated by Django 4.2.17 on 2025-01-06 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_bonus_amount_alter_shoppingcart_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', message='CVV must be 3 or 4 digits long and contain only numbers.')], verbose_name='CVV'),
        ),
    ]
