# Generated by Django 4.2.17 on 2025-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_complaint_customer_complaint_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance'),
        ),
    ]
