# Generated by Django 4.2.17 on 2025-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_creditcard_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DVD',
            field=models.BooleanField(blank=True, null=True, verbose_name='DVD Reader'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fingerprint',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fingerprint Reader'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Gifts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Processor'),
        ),
    ]
